# Generated by Django 6.0.1 on 2026-01-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_in_grams', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date', models.DateTimeField(verbose_name='date purchased')),
                ('total_price_eur', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
